---
output:
  pdf_document: default
  html_document: default
---
# groupedHG 0.1.0

* Initial release.
* The following functions are included and documented for the **Hypergeometric sampling model**:

  - `pmfHG.perfect()`
  - `dpmfHG.perfect()`
  - `FIpmfHG.Tx.perfect()`
  - `qDLkGroup()`
  - `dqDLkGroup()`
  - `pmfHG.imperfect.group`
  - `dpmfHG.imperfect.group()`
  - `qdlkItem()`
  - `dqdlkItem()`
  - `pmfHG.imperfect.item()`
  - `dpmfHG.imperfect.item()`
  - `FIpmfHG.Tx.imperfect()`
  - `FIpmfHG.Tx.imperfect.detail()`
  - `ExpVarHG.imperfect.group()`
  - `ExpVarHG.imperfect.item()`
  - `ExpVarHG.imperfect()`
  - `simGroupedHG()`

* The following functions are included and documented for the **Binomial sampling model**:

  - `pmfBN.perfect()`
  - `pmfBN.imperfect.group()`
  - `pmfBN.imperfect.item()`
  - `FIpmfBN.Tx.perfect()`
  - `FIpmfBN.Tx.imperfect.group()`
  - `FIpmfBN.Tx.imperfect.item()`
  - `FIpmfBN.Tx.imperfect()`
  - `ExpVarBN.imperfect.group()`
  - `ExpVarBN.imperfect.item()`
  - `ExpVarBN.imperfect()`
  - `simGroupedBN()`
